### ISSUE TITLE
Pawword

### ISSUE THREAD

**Issue by LittleKwai** [UCA-MSI/NiPTUNE#4]
Hello, after reading the article, I am very interested in related methods. Hope to get the code of NiPTUME. How can I get the password of Google Form?

**Comment by marcomilanesio** [comment]
Hi.You have to ask the contact author for having access to the code.——-MarcoOn 1 Feb 2023, at 07:40, Xiaokui ***@***.***> wrote:﻿
Hello, after reading the article, I am very interested in related methods. Hope to get the code of NiPTUME. How can I get the password of Google Form?

**Comment by LittleKwai** [comment]
get it, thanks!
